# App Rules
# Example:
# [[appRule]]
# class = "st"
# instance = "st"
# title = "st"
# monitor = 1
# tags = [ 1, 4, 7 ]
# state = "floating" # normal, floating, and fullscreen are all valid.

# Start external programs
[[startProcess]]
command = "pkill nimdow"
keys = [ "Delete" ]
modifiers = [ "control", "alt" ]

[[startProcess]]
command = "$BROWSER"
keys = [ "i" ]
modifiers = [ "super" ]

[[startProcess]]
command = "dmenu_run"
keys = [ "p" ]
modifiers = [ "super" ]

[[startProcess]]
command = "termite"
keys = [ "Return" ]
modifiers = [ "super" ]

[[startProcess]]
command = "flameshot gui"
keys = [ "Print" ]

[autostart]
exec = [
  	"xsetroot -cursor_name left_ptr",
	"nitrogen --restore",
	"pamac-tray",
	"xfce4-power-manager",
  	"nitrogen --restore",
  	"/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1",	
	"volumeicon",
  	"slstatus",
	"/usr/lib/xfce4/notifyd/xfce4-notifyd",
	"picom",
]

[settings]
  # Window settings
  borderWidth = 3
  borderColorUnfocused = "#D4BFFF"
  borderColorFocused = "#63F2F1"
  borderColorUrgent = "#F02E6E"
  # Bar settings
  barHeight = 25
  windowTitlePosition = "center"
  barBackgroundColor = "#2D2B40"
#  barBackgroundColor = "#282a36"
  barForegroundColor = "#A1EFD3"
  barSelectionColor = "#F48FB1"
  barUrgentColor = "#F02E6E"
  barFonts = [
    "monospace:size=10:antialias=true",
    "NotoColorEmoji:size=10:antialias=true"
  ]
	# Layout settings
  gapSize = 12
	resizeStep = 10
  # General settings
  loggingEnabled = false

# Window manager controls
[controls]
  [controls.reloadConfig]
  keys = [ "r" ]
  modifiers = [ "super", "shift" ]

  [controls.focusPrevious]
  keys = [ "k" ]
  modifiers = [ "super" ]

  [controls.focusNext]
  keys = [ "j" ]
  modifiers = [ "super" ]

  [controls.moveWindowPrevious]
  keys = [ "k" ]
  modifiers = [ "super", "shift" ]

  [controls.moveWindowNext]
  keys = [ "space" ]
  modifiers = [ "super" ]

  [controls.toggleFullscreen]
  keys = [ "f" ]
  modifiers = [ "super" ]

  [controls.destroySelectedWindow]
  keys = [ "q" ]
  modifiers = [ "super" ]

  [controls.goToPreviousTag]
  keys = [ "w" ]
  modifiers = [ "super" ]

  [controls.moveWindowToPreviousTag]
  keys = [ "w" ]
  modifiers = [ "super", "shift" ]

  [controls.focusPreviousMonitor]
  keys = [ "comma" ]
  modifiers = [ "super" ]

  [controls.focusNextMonitor]
  keys = [ "period" ]
  modifiers = [ "super" ]

  [controls.moveWindowToPreviousMonitor]
  keys = [ "comma" ]
  modifiers = [ "super", "shift" ]

  [controls.moveWindowToNextMonitor]
  keys = [ "period" ]
  modifiers = [ "super", "shift" ]

  [controls.increaseMasterCount]
  keys = [ "z" ]
  modifiers = [ "super" ]

  [controls.decreaseMasterCount]
  keys = [ "x" ]
  modifiers = [ "super" ]

  [controls.toggleFloating]
  keys = [ "space" ]
  modifiers = [ "super", "shift" ]

  [controls.jumpToUrgentWindow]
  keys = [ "u" ]
  modifiers = [ "super" ]

  [controls.goToTag]
  keys = [ "1", "2", "3", "4", "5", "6", "7", "8", "9" ]
  modifiers = [ "super" ]

  [controls.moveWindowToTag]
  keys = [ "1", "2", "3", "4", "5", "6", "7", "8", "9" ]
  modifiers = [ "super", "shift" ]

  [controls.toggleTagView]
  keys = [ "1", "2", "3", "4", "5", "6", "7", "8", "9" ]
  modifiers = [ "super", "control" ]

  [controls.toggleWindowTag]
  keys = [ "1", "2", "3", "4", "5", "6", "7", "8", "9" ]
  modifiers = [ "super", "shift", "control" ]

	[controls.increaseMasterWidth]
	keys = [ "l" ]
	modifiers = [ "super" ]

	[controls.decreaseMasterWidth]
	keys = [ "h" ]
	modifiers = [ "super" ]

  [controls.moveWindowToScratchpad]
  keys = [ "s" ]
  modifiers = [ "super", "shift" ]

  [controls.popScratchpad]
  keys = [ "s" ]
  modifiers = [ "super" ]

# Example monitor settings:
[monitors]
  [monitors.default.tags]
  1.displayString = "WEB"
  2.displayString = "MSG" 
  3.displayString = "TERM" 
  4.displayString = "RESEARCH" 
  5.displayString = "PROTOTYPES" 
  6.displayString = "TODO" 
  7.displayString = "MUSIC" 
  8.displayString = "MAIL" 
  9.displayString = "SYS" 

# [monitors.default.tags]
  # 1.displayString = "one"
  # 2.displayString = "foobar"
  # Set the number of master windows for ALL monitors.
  # all.numMasterWindows = 2

  # [monitors.1.tags]
  # 2.displayString = "two"
  # Set the number of master windows per-monitor.
  # all.numMasterWindows = 3
  # Set the number of master windows per-tag.
  # 2.numMasterWindows = 1

  # [monitors.2.tags]
  # 2.displayString = "too"

